### PR TITLE
DEP remove appveyor

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by blowekamp** [comment]
We have had problems with the windows builds, I don't believe it is new. The project is dependent on libsimpleitk and libitk. Should those be updated first?

**Comment by beckermr** [comment]
Good to know. We are deprecating appveyor, so I am trying to move any remaining feedstocks to azure. Are these other ones on appveyor too?

**Comment by beckermr** [comment]
Looks like not. Right now, the build on windows cannot find fftw3. Do you have any ideas on that?

**Comment by blowekamp** [comment]
The privious error was related to libitk's CMake files containing unix style paths that were not being post processed to be changed. This is likely the cause of the FFTW error.

**Comment by beckermr** [comment]
Ahhh interesting. Can you point me to where this was fixed and/or happened?

**Comment by blowekamp** [comment]
If you examine the windows [libitk-devel](https://anaconda.org/conda-forge/libitk-devel/files) package, you'll find the following:
```
grep -r libitk_[0-9]\* Library/lib/cmake/
Library/lib/cmake//ITK-5.0/Modules/ITKPNG.cmake:set(ITKPNG_LIBRARIES "D:/bld/libitk_1574524116751/_h_env/Library/lib/libpng.lib;D:/bld/libitk_1574524116751/_h_env/Library/lib/z.lib")
Library/lib/cmake//ITK-5.0/Modules/ITKPNG.cmake:set(ITKPNG_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.0;D:/bld/libitk_1574524116751/_h_env/Library/include;D:/bld/libitk_1574524116751/_h_env/Library/include;D:/bld/libitk_1574524116751/_h_env/Library/include;D:/bld/libitk_1574524116751/_h_env/Library/include")
Library/lib/cmake//ITK-5.0/Modules/ITKTIFF.cmake:set(ITKTIFF_LIBRARIES "D:/bld/libitk_1574524116751/_h_env/Library/lib/tiff.lib")
Library/lib/cmake//ITK-5.0/Modules/ITKTIFF.cmake:set(ITKTIFF_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.0;D:/bld/libitk_1574524116751/_h_env/Library/include")
Library/lib/cmake//ITK-5.0/Modules/ITKJPEG.cmake:set(ITKJPEG_LIBRARIES "D:/bld/libitk_1574524116751/_h_env/Library/lib/jpeg.lib")
Library/lib/cmake//ITK-5.0/Modules/ITKJPEG.cmake:set(ITKJPEG_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.0;D:/bld/libitk_1574524116751/_h_env/Library/include")
```

**Comment by beckermr** [comment]
ouch

**Comment by beckermr** [comment]
This one did not pass. Why was it merged?

**Comment by blowekamp** [comment]
It had the same issues as the prior build. I though it was better not to let this recipe get out of date.

I created an issue is the package causing the problems: conda-forge/libitk-feedstock#43

**Pull request merged**
